- lessons-3rd/lesson-8/grammar-8/index.html
First PR that doesn't involve code changes :crossed_fingers: 
The short form negative of 見る is 見ない, if I'm not mistaken. The answer was expecting a godan conjugation.
> Fix for lesson 8 grammar 8

- lessons-3rd/lesson-2/workbook-4/index.html
> Fix name of person answering

- lessons-3rd/lesson-12/grammar-3/index.html
I got caught on 「ビールを飲みすぎました」so I figured "alcohol" would be more fitting
> More generic beverage in lesson 12 grammar 3

- lessons/lesson-0/workbook-1/index.html
Hello,
The second edition workbook, the greetings, presents the images' numbers of the greetings between the mother and the girl in a different way, this fixes that
Reference image: https://imgur.com/a/VjwCMpB
> fix for second ed workbook to keep the images number

- resources/tools/anki_decks_maker.py
> Fix note creation order by sorting by lesson number then section.

- lessons/lesson-14/grammar-6/index.html
Lesson 14 grammar 6 has もらる instead of もらう
> changed もらる to もらう

- lessons-3rd/lesson-3/workbook-7/index.html
- lessons/lesson-3/workbook-8/index.html
I think this should say "go to bed", not "got to bed", since it is expecting the `します` form, and not referring to an event which happened in the past, but rather to something that happens in general.
Thanks so much for this resource by the way -- this is my favorite study resource and totally changed the game for me when I found it. I've been studying Japanese for a year and wish I learned about this much earlier! It's been a joy going through Genki with this, even covering topics I'm already familiar with from other places. Plus I'm getting really fast with Japanese computer input!
> [typofix] "got to bed" -> "go to bed"

- lessons/lesson-14/workbook-7/index.html
In lesson 14, workbook 7 Section B answer 3a, added 「子ども」as a possible spelling.
> added 子ども as a possible answer

- lessons-3rd/lesson-11/workbook-5/index.html
- lessons/lesson-11/workbook-5/index.html
Adds missing word "had".
(First contribution pull request ever!)
> Add missing word to Lesson 11 - Workbook 5

- lessons-3rd/lesson-10/literacy-wb-2/index.html
> Small typo fix

- lessons-3rd/lesson-18/workbook-8/index.html
> Fix English typo in Lesson 18 Workbook 8

- lessons-3rd/lesson-13/grammar-1/index.html
Wrong: 話なす
Corrected: 話す
There is an extra な.
> Typo for 話なす

- lessons-3rd/lesson-21/workbook-8/index.html
> Fix 3rd edition typo, Workbook Lesson 8

- README.md
Just found about this repository. Maybe Jotoba makes a good addition to this one as well?
> Add Jotoba

- lessons/lesson-17/workbook-5/index.html
This also removes a bunch of whitespace that my formatter automatically removed. Happy to make those changes in a separate PR but I think the diff is still readable and the changes are low-risk :).
> Allow 鍵 in place of かぎ.

- lessons-3rd/lesson-22/grammar-7/index.html
> Fix typo がんばろ => がんばる

- lessons-3rd/lesson-23/grammar-1/index.html
edited な into う in the necessary answer section
> 受ける incorrectly written as nakeru in answer

- lessons-3rd/lesson-5/grammar-8/index.html
The problem in the book only requires replacing the part after 休みに
> Lesson 5 grammar 8 is meant to repeat 休みに

- lessons-3rd/lesson-18/workbook-6/index.html
> Typo fix in lesson 16 workbook 6

- lessons-3rd/lesson-8/grammar-5/index.html
> Remove を between 料理 and する

- README.md
fix broken genki self study room link
> fix broken genki self study room link

- resources/javascript/jisho.js
> Typo fix jisho.js
